### ISSUE TITLE
in.telnetd crashes on running Nessus security scan

### ISSUE THREAD

**Issue by parkrish** [marado/netkit-telnet#3]
Problem:
=======
The in.telnetd process is seen to crash on running Nessus security scan.

in.telnetd version
==============
telnetd_0.17-41_amd64.deb  (Debian stretch image)

Possible root cause:
=================
1) The telnetd process invokes netflush() to flush() data 

root@OS10:~# #154080 0x00007f681f34a8d9 in _IO_new_do_write (fp=<optimized out>, data=<optimized out>, to_do=1350) at fileops.c:502
root@OS10:~# #154081 0x00007f681f348978 in _IO_new_file_sync (fp=0x55a7d9b45150) at fileops.c:882
root@OS10:~# #154082 0x00007f681f33e03c in __GI__IO_fflush (fp=0x55a7d9b45150) at iofflush.c:40
root@OS10:~# #154083 0x000055a7d97f95a0 in netflush () at utility.c:325
root@OS10:~# #154084 0x000055a7d97f95d6 in ttloop () at utility.c:81
root@OS10:~# #154085 0x000055a7d97f5c55 in getterminaltype (name=0x7ffe09676c70 "") at telnetd.c:484
root@OS10:~# #154086 doit (who_len=16, who=0x7ffe09676bf0) at telnetd.c:722
root@OS10:~# #154087 main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at telnetd.c:402

2)Error is encountered while flushing.This results in invocation of cleanup function

oot@OS10:~# #154071 0x00007f681f34c4cc in _IO_flush_all_lockp (do_lock=do_lock@entry=0) at genops.c:792
root@OS10:~# #154072 0x00007f681f34c695 in _IO_cleanup () at genops.c:957
root@OS10:~# #154073 0x00007f681f30c8e3 in __run_exit_handlers (status=0, listp=<optimized out>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:96
root@OS10:~# #154074 0x00007f681f30c99a in __GI_exit (status=<optimized out>) at exit.c:105
root@OS10:~# #154075 0x000055a7d97f8fd2 in cleanup (sig=sig@entry=0) at sys_term.c:736
root@OS10:~# #154076 0x000055a7d97f92d0 in netwritebuf () at utility.c:288
root@OS10:~# #154077 0x000055a7d97f94be in netwrite (cookie=<optimized out>,

3)The cleanup function invokes exit(0), which in turn trigger flushing again. The flushing encounters the error again ,resulting in continuous loop.

root@OS10:~# #154070 0x00007f681f34a8d9 in _IO_new_do_write (fp=<optimized out>, data=<optimized out>, to_do=1350) at fileops.c:502
root@OS10:~# #154071 0x00007f681f34c4cc in _IO_flush_all_lockp (do_lock=do_lock@entry=0) at genops.c:792
root@OS10:~# #154072 0x00007f681f34c695 in _IO_cleanup () at genops.c:957
root@OS10:~# #154073 0x00007f681f30c8e3 in __run_exit_handlers (status=0, listp=<optimized out>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:96
root@OS10:~# #154074 0x00007f681f30c99a in __GI_exit (status=<optimized out>) at exit.c:105
root@OS10:~# #154075 0x000055a7d97f8fd2 in cleanup (sig=sig@entry=0) at sys_term.c:736

Back trace
==========

Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/in.telnetd...Reading symbols from /usr/lib/debug/.build-id/f7/8762784cef671474d6d52981133d7b47d721a9.debug...done.
done.
[New LWP 14372]
Core was generated by `in.telnetd'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  getutline_r_file (line=0x7ffd5faa11d0, buffer=0x7ffd5faa1350, result=0x7ffd5faa11b8) at ../login/utmp_file.c:344
344     ../login/utmp_file.c: No such file or directory.
(gdb) bt
#0  getutline_r_file (line=0x7ffd5faa11d0, buffer=0x7ffd5faa1350, result=0x7ffd5faa11b8) at ../login/utmp_file.c:344
#1  0x00007f3154c310e9 in __getutline_r (line=line@entry=0x7ffd5faa11d0, buffer=buffer@entry=0x7ffd5faa1350, result=result@entry=0x7ffd5faa11b8) at getutline_r.c:39
#2  0x00007f3154eb42b0 in logout (line=line@entry=0x563f3af744a5 "pts/3") at logout.c:45
#3  0x0000563f39db1fb5 in cleanup (sig=sig@entry=0) at sys_term.c:734
#4  0x0000563f39db22d0 in netwritebuf () at utility.c:288
#5  0x0000563f39db24be in netwrite (cookie=<optimized out>,
    buf=0x563f3af768f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374"..., len=<optimized out>) at utility.c:1250
#6  0x00007f3154b7b65e in _IO_cookie_write (fp=0x563f3af72150, buf=<optimized out>, size=1536) at iofopncook.c:72
#7  0x00007f3154b85b62 in new_do_write (fp=0x563f3af72150,
    data=0x563f3af762f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374"..., to_do=to_do@entry=1536) at fileops.c:526
#8  0x00007f3154b878d9 in _IO_new_do_write (fp=<optimized out>, data=<optimized out>, to_do=1536) at fileops.c:502
#9  0x00007f3154b894cc in _IO_flush_all_lockp (do_lock=do_lock@entry=0) at genops.c:792
#10 0x00007f3154b89695 in _IO_cleanup () at genops.c:957
#11 0x00007f3154b498e3 in __run_exit_handlers (status=0, listp=<optimized out>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:96
#12 0x00007f3154b4999a in __GI_exit (status=<optimized out>) at exit.c:105
#13 0x0000563f39db1fd2 in cleanup (sig=sig@entry=0) at sys_term.c:736
#14 0x0000563f39db22d0 in netwritebuf () at utility.c:288
#15 0x0000563f39db24be in netwrite (cookie=<optimized out>,
    buf=0x563f3af768f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374"..., len=<optimized out>) at utility.c:1250
#16 0x00007f3154b7b65e in _IO_cookie_write (fp=0x563f3af72150, buf=<optimized out>, size=1536) at iofopncook.c:72
#17 0x00007f3154b85b62 in new_do_write (fp=0x563f3af72150,
    data=0x563f3af762f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374"..., to_do=to_do@entry=1536) at fileops.c:526
#18 0x00007f3154b878d9 in _IO_new_do_write (fp=<optimized out>, data=<optimized out>, to_do=1536) at fileops.c:502
#19 0x00007f3154b894cc in _IO_flush_all_lockp (do_lock=do_lock@entry=0) at genops.c:792
#20 0x00007f3154b89695 in _IO_cleanup () at genops.c:957
#21 0x00007f3154b498e3 in __run_exit_handlers (status=0, listp=<optimized out>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:96
#22 0x00007f3154b4999a in __GI_exit (status=<optimized out>) at exit.c:105
#23 0x0000563f39db1fd2 in cleanup (sig=sig@entry=0) at sys_term.c:736
#24 0x0000563f39db22d0 in netwritebuf () at utility.c:288
#25 0x0000563f39db24be in netwrite (cookie=<optimized out>,
    buf=0x563f3af768f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\37---Type <return> to continue, or q <return> to quit---
7\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374"..., len=<optimized out>) at utility.c:1250
#26 0x00007f3154b7b65e in _IO_cookie_write (fp=0x563f3af72150, buf=<optimized out>, size=1536) at iofopncook.c:72
#27 0x00007f3154b85b62 in new_do_write (fp=0x563f3af72150,
    data=0x563f3af762f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374"..., to_do=to_do@entry=1536) at fileops.c:526
#28 0x00007f3154b878d9 in _IO_new_do_write (fp=<optimized out>, data=<optimized out>, to_do=1536) at fileops.c:502
#29 0x00007f3154b894cc in _IO_flush_all_lockp (do_lock=do_lock@entry=0) at genops.c:792
#30 0x00007f3154b89695 in _IO_cleanup () at genops.c:957
#31 0x00007f3154b498e3 in __run_exit_handlers (status=0, listp=<optimized out>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:96
#32 0x00007f3154b4999a in __GI_exit (status=<optimized out>) at exit.c:105
#33 0x0000563f39db1fd2 in cleanup (sig=sig@entry=0) at sys_term.c:736
#34 0x0000563f39db22d0 in netwritebuf () at utility.c:288
#35 0x0000563f39db24be in netwrite (cookie=<optimized out>,
    buf=0x563f3af768f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374"..., len=<optimized out>) at utility.c:1250
#36 0x00007f3154b7b65e in _IO_cookie_write (fp=0x563f3af72150, buf=<optimized out>, size=1536) at iofopncook.c:72
#37 0x00007f3154b85b62 in new_do_write (fp=0x563f3af72150,
    data=0x563f3af762f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374"..., to_do=to_do@entry=1536) at fileops.c:526
#38 0x00007f3154b878d9 in _IO_new_do_write (fp=<optimized out>, data=<optimized out>, to_do=1536) at fileops.c:502
#39 0x00007f3154b894cc in _IO_flush_all_lockp (do_lock=do_lock@entry=0) at genops.c:792
#40 0x00007f3154b89695 in _IO_cleanup () at genops.c:957
#41 0x00007f3154b498e3 in __run_exit_handlers (status=0, listp=<optimized out>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:96
#42 0x00007f3154b4999a in __GI_exit (status=<optimized out>) at exit.c:105
#43 0x0000563f39db1fd2 in cleanup (sig=sig@entry=0) at sys_term.c:736
#44 0x0000563f39db22d0 in netwritebuf () at utility.c:288
#45 0x0000563f39db24be in netwrite (cookie=<optimized out>,
    buf=0x563f3af768f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374"..., len=<optimized out>) at utility.c:1250
#46 0x00007f3154b7b65e in _IO_cookie_write (fp=0x563f3af72150, buf=<optimized out>, size=1536) at iofopncook.c:72
#47 0x00007f3154b85b62 in new_do_write (fp=0x563f3af72150,
    data=0x563f3af762f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374"..., to_do=to_do@entry=1536) at fileops.c:526
---Type <return> to continue, or q <return> to quit---
#48 0x00007f3154b878d9 in _IO_new_do_write (fp=<optimized out>, data=<optimized out>, to_do=1536) at fileops.c:502
#49 0x00007f3154b894cc in _IO_flush_all_lockp (do_lock=do_lock@entry=0) at genops.c:792
#50 0x00007f3154b89695 in _IO_cleanup () at genops.c:957
#51 0x00007f3154b498e3 in __run_exit_handlers (status=0, listp=<optimized out>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:96
#52 0x00007f3154b4999a in __GI_exit (status=<optimized out>) at exit.c:105
#53 0x0000563f39db1fd2 in cleanup (sig=sig@entry=0) at sys_term.c:736
#54 0x0000563f39db22d0 in netwritebuf () at utility.c:288
#55 0x0000563f39db24be in netwrite (cookie=<optimized out>,
    buf=0x563f3af768f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374"..., len=<optimized out>) at utility.c:1250
#56 0x00007f3154b7b65e in _IO_cookie_write (fp=0x563f3af72150, buf=<optimized out>, size=1536) at iofopncook.c:72
#57 0x00007f3154b85b62 in new_do_write (fp=0x563f3af72150,
    data=0x563f3af762f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374"..., to_do=to_do@entry=1536) at fileops.c:526
#58 0x00007f3154b878d9 in _IO_new_do_write (fp=<optimized out>, data=<optimized out>, to_do=1536) at fileops.c:502
#59 0x00007f3154b894cc in _IO_flush_all_lockp (do_lock=do_lock@entry=0) at genops.c:792
#60 0x00007f3154b89695 in _IO_cleanup () at genops.c:957
#61 0x00007f3154b498e3 in __run_exit_handlers (status=0, listp=<optimized out>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:96
#62 0x00007f3154b4999a in __GI_exit (status=<optimized out>) at exit.c:105
#63 0x0000563f39db1fd2 in cleanup (sig=sig@entry=0) at sys_term.c:736
#64 0x0000563f39db22d0 in netwritebuf () at utility.c:288
#65 0x0000563f39db24be in netwrite (cookie=<optimized out>,
    buf=0x563f3af768f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374"..., len=<optimized out>) at utility.c:1250
#66 0x00007f3154b7b65e in _IO_cookie_write (fp=0x563f3af72150, buf=<optimized out>, size=1536) at iofopncook.c:72
#67 0x00007f3154b85b62 in new_do_write (fp=0x563f3af72150,
    data=0x563f3af762f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374"..., to_do=to_do@entry=1536) at fileops.c:526
#68 0x00007f3154b878d9 in _IO_new_do_write (fp=<optimized out>, data=<optimized out>, to_do=1536) at fileops.c:502
#69 0x00007f3154b894cc in _IO_flush_all_lockp (do_lock=do_lock@entry=0) at genops.c:792
#70 0x00007f3154b89695 in _IO_cleanup () at genops.c:957
#71 0x00007f3154b498e3 in __run_exit_handlers (status=0, listp=<optimized out>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:96.....
#72 0x00007f3154b4999a in __GI_exit (status=<optimized out>) at exit.c:105
#73 0x0000563f39db1fd2 in cleanup (sig=sig@entry=0) at sys_term.c:736
#74 0x0000563f39db22d0 in netwritebuf () at utility.c:288
#75 0x0000563f39db24be in netwrite (cookie=<optimized out>,
    buf=0x563f3af768f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\---Type <return> to continue, or q <return> to quit---
....
....
#154051 0x00007f3154b498e3 in __run_exit_handlers (status=0, listp=<optimized out>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:96
#154052 0x00007f3154b4999a in __GI_exit (status=<optimized out>) at exit.c:105
#154053 0x0000563f39db1fd2 in cleanup (sig=sig@entry=0) at sys_term.c:736
#154054 0x0000563f39db22d0 in netwritebuf () at utility.c:288
#154055 0x0000563f39db24be in netwrite (cookie=<optimized out>,
    buf=0x563f3af768f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374"..., len=<optimized out>) at utility.c:1250
#154056 0x00007f3154b7b65e in _IO_cookie_write (fp=0x563f3af72150, buf=<optimized out>, size=1536) at iofopncook.c:72
#154057 0x00007f3154b85b62 in new_do_write (fp=0x563f3af72150,
    data=0x563f3af762f0 "\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374\377\377\374"..., to_do=to_do@entry=1536) at fileops.c:526
#154058 0x00007f3154b878d9 in _IO_new_do_write (fp=<optimized out>, data=<optimized out>, to_do=1536) at fileops.c:502
#154059 0x00007f3154b85978 in _IO_new_file_sync (fp=0x563f3af72150) at fileops.c:882
#154060 0x00007f3154b7b03c in __GI__IO_fflush (fp=0x563f3af72150) at iofflush.c:40
#154061 0x0000563f39db25a0 in netflush () at utility.c:325
#154062 0x0000563f39db26e0 in netclear () at utility.c:235
#154063 0x0000563f39db1285 in telrcv () at state.c:194
#154064 0x0000563f39db261d in ttloop () at utility.c:92
#154065 0x0000563f39daec55 in getterminaltype (name=0x7ffd6029f750 "") at telnetd.c:484
#154066 doit (who_len=16, who=0x7ffd6029f6d0) at telnetd.c:722
#154067 main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at telnetd.c:402

**Comment by marado** [comment]
Hi @parkrish ! Thanks for the bug report. However, this is not the right place to submit issues on debian's telnetd: do it here instead:
https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=telnetd;dist=unstable

**Comment by parkrish** [comment]
Thanks @marado for the information. I have created Debian bug  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=974428 for this issue.
